version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@database:5432/mydb
  #   depends_on:
  #     - database
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules

  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
