import { ImageDrinks } from "@/assets/food";
import { Prisma, PrismaClient } from "@prisma/client";

export default async function run(prisma: PrismaClient) {
  console.info("Seed drinks...");

  const drinks: Array<Prisma.DrinkCreateManyInput> = [
    {
      id: "1",
      name: "Air Mineral",
      calories: 0,
      carbohydrates: 0,
      protein: 0,
      fat: 0,
      sugar: 0,
      isAlcoholic: false,
      servingSize: "250ml",
      image: ImageDrinks.airMineral,
      foodId: "1",
    },
    {
      id: "2",
      name: "Teh Manis",
      calories: 70,
      carbohydrates: 18,
      protein: 0,
      fat: 0,
      sugar: 15,
      isAlcoholic: false,
      servingSize: "250ml",
      image: ImageDrinks.tehManis,
      foodId: "2",
    },
    {
      id: "3",
      name: "Kopi Hitam",
      calories: 2,
      carbohydrates: 0,
      protein: 0,
      fat: 0,
      sugar: 0,
      isAlcoholic: false,
      servingSize: "250ml",
      image: ImageDrinks.kopiHitam,
      foodId: "3",
    },
    {
      id: "4",
      name: "Jus Jeruk",
      calories: 112,
      carbohydrates: 26,
      protein: 2,
      fat: 0.5,
      sugar: 20,
      isAlcoholic: false,
      servingSize: "250ml",
      image: ImageDrinks.jusJeruk,
      foodId: "4",
    },
    {
      id: "5",
      name: "Soda",
      calories: 150,
      carbohydrates: 39,
      protein: 0,
      fat: 0,
      sugar: 39,
      isAlcoholic: false,
      servingSize: "330ml",
      image: ImageDrinks.soda,
      foodId: "5",
    },
    {
      id: "6",
      name: "Bir",
      calories: 150,
      carbohydrates: 13,
      protein: 1,
      fat: 0,
      sugar: 0,
      isAlcoholic: true,
      servingSize: "330ml",
      image: ImageDrinks.bir,
      foodId: "6",
    },
    {
      id: "7",
      name: "Anggur Merah",
      calories: 85,
      carbohydrates: 22,
      protein: 0.5,
      fat: 0,
      sugar: 18,
      isAlcoholic: true,
      servingSize: "150ml",
      image: ImageDrinks.anggurMerah,
      foodId: "7",
    },
    {
      id: "8",
      name: "Jus Apel",
      calories: 110,
      carbohydrates: 29,
      protein: 0,
      fat: 0.1,
      sugar: 25,
      isAlcoholic: false,
      servingSize: "250ml",
      image: ImageDrinks.jusApel,
      foodId: "8",
    },
    {
      id: "9",
      name: "Smoothie Buah",
      calories: 150,
      carbohydrates: 36,
      protein: 2,
      fat: 1,
      sugar: 28,
      isAlcoholic: false,
      servingSize: "250ml",
      image: ImageDrinks.smoothieBuah,
      foodId: "9",
    },
    {
      id: "10",
      name: "Susu",
      calories: 100,
      carbohydrates: 12,
      protein: 8,
      fat: 5,
      sugar: 11,
      isAlcoholic: false,
      servingSize: "250ml",
      image: ImageDrinks.susu,
      foodId: "10",
    },
  ];

  await Promise.all(
    drinks.map(async (drink) => {
      await prisma.drink.upsert({
        where: { id: drink.id },
        update: drink,
        create: drink,
      });
    })
  );
}
