import { ImageFruits } from "@/assets/food";
import { Prisma, PrismaClient } from "@prisma/client";

export default async function run(prisma: PrismaClient) {
  console.info("Seed fruits...");

  const fruits: Array<Prisma.FruitCreateManyInput> = [
    {
      id: "1",
      name: "Apel",
      calories: 52,
      carbohydrates: 14,
      protein: 0.3,
      fat: 0.2,
      sugar: 10,
      isTropical: false,
      servingSize: "100g",
      image: ImageFruits.apel,
      foodId: "1",
    },
    {
      id: "2",
      name: "Pisang",
      calories: 89,
      carbohydrates: 23,
      protein: 1.1,
      fat: 0.3,
      sugar: 12,
      isTropical: true,
      servingSize: "100g",
      image: ImageFruits.pisang,
      foodId: "2",
    },
    {
      id: "3",
      name: "Mangga",
      calories: 60,
      carbohydrates: 15,
      protein: 0.8,
      fat: 0.4,
      sugar: 14,
      isTropical: true,
      servingSize: "100g",
      image: ImageFruits.mangga,
      foodId: "3",
    },
    {
      id: "4",
      name: "Jeruk",
      calories: 47,
      carbohydrates: 12,
      protein: 0.9,
      fat: 0.1,
      sugar: 9,
      isTropical: false,
      servingSize: "100g",
      image: ImageFruits.jeruk,
      foodId: "4",
    },
    {
      id: "5",
      name: "Nanas",
      calories: 50,
      carbohydrates: 13,
      protein: 0.5,
      fat: 0.1,
      sugar: 10,
      isTropical: true,
      servingSize: "100g",
      image: ImageFruits.nanas,
      foodId: "5",
    },
    {
      id: "6",
      name: "Strawberry",
      calories: 32,
      carbohydrates: 7.7,
      protein: 0.7,
      fat: 0.3,
      sugar: 4.9,
      isTropical: false,
      servingSize: "100g",
      image: ImageFruits.strawberry,
      foodId: "6",
    },
    {
      id: "7",
      name: "Kiwi",
      calories: 61,
      carbohydrates: 15,
      protein: 1.1,
      fat: 0.5,
      sugar: 9,
      isTropical: false,
      servingSize: "100g",
      image: ImageFruits.kiwi,
      foodId: "7",
    },
    {
      id: "8",
      name: "Delima",
      calories: 83,
      carbohydrates: 18,
      protein: 1.7,
      fat: 1.2,
      sugar: 13,
      isTropical: false,
      servingSize: "100g",
      image: ImageFruits.delima,
      foodId: "8",
    },
    {
      id: "9",
      name: "Buah Pir",
      calories: 57,
      carbohydrates: 15,
      protein: 0.4,
      fat: 0.1,
      sugar: 10,
      isTropical: false,
      servingSize: "100g",
      image: ImageFruits.buahPir,
      foodId: "9",
    },
    {
      id: "10",
      name: "Semangka",
      calories: 30,
      carbohydrates: 8,
      protein: 0.6,
      fat: 0.2,
      sugar: 6,
      isTropical: true,
      servingSize: "100g",
      image: ImageFruits.semangka,
      foodId: "10",
    },
  ];

  await Promise.all(
    fruits.map(async (fruit) => {
      await prisma.fruit.upsert({
        where: { id: fruit.id },
        update: fruit,
        create: fruit,
      });
    })
  );
}
