import { ImageSnacks } from "@/assets/food";
import { Prisma, PrismaClient } from "@prisma/client";

export default async function run(prisma: PrismaClient) {
  console.info("Seed snacks...");

  const snacks: Array<Prisma.SnackCreateManyInput> = [
    {
      id: "1",
      name: "Keripik Kentang",
      calories: 152,
      carbohydrates: 15,
      protein: 2,
      fat: 10,
      sugar: 1,
      isProcessed: true,
      servingSize: "30g",
      image: ImageSnacks.keripikKentang,
      foodId: "1",
    },
    {
      id: "2",
      name: "Kacang Panggang",
      calories: 166,
      carbohydrates: 6,
      protein: 7,
      fat: 14,
      sugar: 1,
      isProcessed: true,
      servingSize: "30g",
      image: ImageSnacks.kacangPanggang,
      foodId: "2",
    },
    {
      id: "3",
      name: "Popcorn",
      calories: 387,
      carbohydrates: 78,
      protein: 12,
      fat: 7,
      sugar: 0,
      isProcessed: true,
      servingSize: "100g",
      image: ImageSnacks.popcorn,
      foodId: "3",
    },
    {
      id: "4",
      name: "Cokelat",
      calories: 546,
      carbohydrates: 61,
      protein: 4,
      fat: 31,
      sugar: 48,
      isProcessed: true,
      servingSize: "100g",
      image: ImageSnacks.coklat,
      foodId: "4",
    },
    {
      id: "5",
      name: "Biskuit",
      calories: 502,
      carbohydrates: 72,
      protein: 6,
      fat: 23,
      sugar: 22,
      isProcessed: true,
      servingSize: "100g",
      image: ImageSnacks.biskuit,
      foodId: "5",
    },
    {
      id: "6",
      name: "Pisang Goreng",
      calories: 198,
      carbohydrates: 24,
      protein: 1,
      fat: 10,
      sugar: 6,
      isProcessed: false,
      servingSize: "50g",
      image: ImageSnacks.pisangGoreng,
      foodId: "6",
    },
    {
      id: "7",
      name: "Chips",
      calories: 150,
      carbohydrates: 15,
      protein: 2,
      fat: 10,
      sugar: 1,
      isProcessed: true,
      servingSize: "30g",
      image: ImageSnacks.chips,
      foodId: "7",
    },
    {
      id: "8",
      name: "Kue Kering",
      calories: 485,
      carbohydrates: 60,
      protein: 6,
      fat: 25,
      sugar: 25,
      isProcessed: true,
      servingSize: "100g",
      image: ImageSnacks.kueKering,
      foodId: "8",
    },
    {
      id: "9",
      name: "Granola Bar",
      calories: 250,
      carbohydrates: 35,
      protein: 10,
      fat: 10,
      sugar: 10,
      isProcessed: true,
      servingSize: "40g",
      image: ImageSnacks.granolaBar,
      foodId: "9",
    },
    {
      id: "10",
      name: "Kacang Polong",
      calories: 123,
      carbohydrates: 20,
      protein: 7,
      fat: 2,
      sugar: 1,
      isProcessed: true,
      servingSize: "30g",
      image: ImageSnacks.kacangPolong,
      foodId: "10",
    },
  ];

  await Promise.all(
    snacks.map(async (snack) => {
      await prisma.snack.upsert({
        where: { id: snack.id },
        update: snack,
        create: snack,
      });
    })
  );
}
