import { ImageVegetables } from "@/assets/food";
import { Prisma, PrismaClient } from "@prisma/client";

export default async function run(prisma: PrismaClient) {
  console.info("Seed vegetables...");

  const vegetables: Array<Prisma.VegetableCreateManyInput> = [
    {
      id: "1",
      name: "Brokoli",
      calories: 55,
      carbohydrates: 11,
      protein: 3.7,
      fat: 0.6,
      isLeafy: false,
      isRoot: false,
      servingSize: "100g",
      image: ImageVegetables.brokoli,
      foodId: "1",
    },
    {
      id: "2",
      name: "Bayam",
      calories: 23,
      carbohydrates: 3.6,
      protein: 2.9,
      fat: 0.4,
      isLeafy: true,
      isRoot: false,
      servingSize: "100g",
      image: ImageVegetables.bayam,
      foodId: "2",
    },
    {
      id: "3",
      name: "Kembang Kol",
      calories: 25,
      carbohydrates: 5,
      protein: 2,
      fat: 0.3,
      isLeafy: false,
      isRoot: false,
      servingSize: "100g",
      image: ImageVegetables.kembangKol,
      foodId: "3",
    },
    {
      id: "4",
      name: "Wortel",
      calories: 41,
      carbohydrates: 10,
      protein: 0.9,
      fat: 0.2,
      isLeafy: false,
      isRoot: true,
      servingSize: "100g",
      image: ImageVegetables.wortel,
      foodId: "4",
    },
    {
      id: "5",
      name: "Tomat",
      calories: 18,
      carbohydrates: 3.9,
      protein: 0.9,
      fat: 0.2,
      isLeafy: false,
      isRoot: false,
      servingSize: "100g",
      image: ImageVegetables.tomat,
      foodId: "5",
    },
    {
      id: "6",
      name: "Kacang Hijau",
      calories: 347,
      carbohydrates: 57,
      protein: 25,
      fat: 1.2,
      isLeafy: false,
      isRoot: true,
      servingSize: "100g",
      image: ImageVegetables.kacangHijau,
      foodId: "6",
    },
    {
      id: "7",
      name: "Lobak",
      calories: 18,
      carbohydrates: 4.1,
      protein: 0.6,
      fat: 0.1,
      isLeafy: false,
      isRoot: true,
      servingSize: "100g",
      image: ImageVegetables.lobak,
      foodId: "7",
    },
    {
      id: "8",
      name: "Kacang Panjang",
      calories: 47,
      carbohydrates: 7.6,
      protein: 2.8,
      fat: 0.2,
      isLeafy: false,
      isRoot: false,
      servingSize: "100g",
      image: ImageVegetables.kacangPanjang,
      foodId: "8",
    },
    {
      id: "9",
      name: "Kailan",
      calories: 39,
      carbohydrates: 7,
      protein: 3.7,
      fat: 0.6,
      isLeafy: true,
      isRoot: false,
      servingSize: "100g",
      image: ImageVegetables.kailan,
      foodId: "9",
    },
    {
      id: "10",
      name: "Zucchini",
      calories: 17,
      carbohydrates: 3.1,
      protein: 1.2,
      fat: 0.3,
      isLeafy: false,
      isRoot: false,
      servingSize: "100g",
      image: ImageVegetables.zucchini,
      foodId: "10",
    },
  ];

  await Promise.all(
    vegetables.map(async (vegetable) => {
      await prisma.vegetable.upsert({
        where: { id: vegetable.id },
        update: vegetable,
        create: vegetable,
      });
    })
  );
}
